config/routes.rb
Rails.application.routes.draw do
  captcha_route
  resources :planes
  resources :catalogos
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  post '/rate' => 'rater#create', :as => 'rate'
  resources :catalogos
  resources :categories 
  devise_for :enterprises do
    get '/enterprises/sign_out' => 'devise/sessions#destroy'
end
resources :enterprises do
  resources :answers
end

  devise_for :clients
  root :to => "home#index"
  resources :paginaclients
  resources :paginaentreprise

  #Papa cliente hijo cotizacion
  resources :clients do
  	resources :cotizacions
    resources :calificacions
  end
  get '/solicitudes' => "paginaentrerprise#cotizacionesempresa"
  get '/cotizaciones' => "paginaentrerprise#cotizaciones"
  get '/catalogo' => 'categories#catalogo'
 
  get '/perfil' => 'profile#perfil'
 
  get '/clientes' => 'paginaclients#pageclient'
  get '/profesionales' => 'paginaentrerprise#pagenterprise'

  get '/respuestas_recibidas'=>'paginaclients#respuestas'

  get '/respuesta_aceptada'=>'paginaclients#answer_success'
  get '/nueva_contrasena' => 'paginaclients#new'

  get '/mis_calificaciones' => 'paginaentrerprise#calificacion'


  resources :payments
end

app/models/cotizacion.rb
class Cotizacion < ApplicationRecord
	has_many :answers
	belongs_to :client
	belongs_to :enterprise
	belongs_to :category
	validates :descripcion, :tiempo, :sector, :area, :provincia,:category_id, presence: true
	validates_inclusion_of :area, :in => %w(rural urbano)
	validates_inclusion_of :sector, :in => %w(publico privado)
	validates_inclusion_of :tiempo, :in => %w(soon 1a3 mas)
	
end

app/controllers/cotizacions_controller.rb
class CotizacionsController < ApplicationController
  
  before_action :set_client,only: [:show, :edit, :update, :destroy]
  before_action :authenticate_client!

  # GET /cotizacions
  # GET /cotizacions.json

  def index
    @client = current_client
    @cotizacions= Cotizacion.where(client_id: @client.id)
  end

  # GET /cotizacions/1
  # GET /cotizacions/1.json
  def show
    @client = current_client
    @cotizacion = Cotizacion.find(params[:client_id])
  end

  # GET /cotizacions/new
  def new
    @client = current_client
    if params[:enterprise_id]
      @cotizacion=@client.cotizacions.new
      @cotizacion.enterprise_id = params[:enterprise_id]
    
    else
      @cotizacion = @client.cotizacions.new
    end
  end

  # GET /cotizacions/1/edit
  def edit
      @client=current_client
      @cotizacion = Cotizacion.find(params[:id])
    
  end

  # POST /cotizacions
  # POST /cotizacions.json
  #diegonadas

  #Asociacion de id cliente con cotizacion
  def create
    @client = current_client
    @cotizacion = @client.cotizacions.new(cotizacion_params)
   
    if @client.save
      flash[:notice]= "A agregado una nueva cotizacion"
      redirect_to client_cotizacions_path(params[:client_id])
    else
      render :new
    end
  end

  # PATCH/PUT /cotizacions/1
  # PATCH/PUT /cotizacions/1.json

  def update
    @client =current_client
    @cotizacion = Cotizacion.find(params[:id])
     if @cotizacion.update(cotizacion_params)
      flash[:notice]= "Has editado la cotizacion"
      redirect_to client_cotizacions_path(params[:client_id])
    else
      render :edit
    end
  end

  # DELETE /cotizacions/1
  # DELETE /cotizacions/1.json
  def destroy
   @client = current_client
   @cotizacion =Cotizacion.find(params[:id])
   if @cotizacion.destroy
    flash[:notice]="Has eliminado la cotizacion"
    redirect_to client_cotizacions_path(params[:client_id])
  end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    
  
    # Never trust parameters from the scary internet, only allow the white list through.
    def cotizacion_params
      params.require(:cotizacion).permit(:id,:answer_id,:enterprise_id,:descripcion, :estado,:category_id, :client_id, :area, :sector, :tiempo, :provincia)
    end

    def set_client
      @client = Client.find(params[:client_id])
    end
   
    
end

app/helpers/cotizacions_helper.rb
module CotizacionsHelper
end

app/views/cotizacions/_form.html.erb
 <%region= {"Región Metropolitana - Melipilla" => "melipilla",
 "Región Metropolitana - Chacabuco" => 'chacabuco',
 'Región Metropolitana - Maipo'=>'maipo',
 'Región Metropolitana - Cordillera'=>'cordillera',
 'Región Metropolitana - Talagante'=>'talagante',
 'Región Metropolitana - Santiago'=>'santiago',
 'Región I Tarapacá - Iquique'=>'iquique',
 'Región I Tarapacá - Tamarugal'=>'tamarugal',
 'Región II Antofagasta - El Loa'=>'el-loa',
 'Región II Antofagasta - Tocopilla'=>'tocopilla',
 'Región II Antofagasta - Antofagasta'=> 'antofagasta',
 'Región III Atacama - Copiapó'=>'copiapo',
 'Región III Atacama - Chañaral'=>'chanaral',
 'Región III Atacama - Huasco'=>'huasco',
 'Región IV Coquimbo - Choapa'=>'choapa',
 'Región IV Coquimbo - Limarí'=>'limari',
 'Región IV Coquimbo - Elqui'=>'elqui',
 'Región V Valparaíso - San Felipe de Aconcagua'=>'san-felipe-de-aconcagua',
 'Región V Valparaíso - Isla de Pascua'=>'isla-de-pascua',
 'Región V Valparaíso - Valparaíso'=>'valparaiso',
 'Región V Valparaíso - San Antonio'=>'san-antonio',
 'Región V Valparaíso – Marga Marga'=>'marga-marga',
 'Región V Valparaíso - Los Andes'=>'los-andes',
 'Región V Valparaíso - Quillota'=>'quillota',
 'Región V Valparaíso - Petorca'=>'petorca',
 'Región VI Libertador B. OHiggins - Cardenal Caro'=>'cardenal-caro',
 "Región VI Libertador B. O'Higgins - Cachapoal"=>'cachapoal',
 "Región VI Libertador B. O'Higgins - Colchagua"=>'colchagua',
 "Región VII Maule - Cauquenes"=>'cauquenes',
 'Región VII Maule - Talca'=>'talca',
 'Región VII Maule - Linares'=>'linares',
 'Región VII Maule - Curicó'=>'curico',
 'Región VIII Biobío - Arauco'=>'arauco',
 'Región VIII Biobío - Ñuble'=>'nuble',
 'Región VIII Biobío - Concepción'=>'concepcion',
 'Región VIII Biobío - biobio'=>'bio-bio',
 'Región IX La Araucanía - Malleco'=>'malleco',
 'Región IX La Araucanía - Cautín'=>'cautin',
 'Región X Los Lagos - Llanquihue'=>'llanquihue',
 'Región X Los Lagos - Palena'=>'palena',
 'Región X Los Lagos - Osorno'=>'osorno',
 'Región X Los Lagos - Chiloé'=>'chiloe',
 'Región XI Aysen - Aysen'=>'aysen',
 'Región XI Aysen - Capitán Prat'=>'capitan-prat',
 'Región XI Aysen - General Carrera'=>'general-carrera',
 'Región XI Aysen - Coihaique'=>'coihaique',
 'Región XII Magallanes - Antártica Chilena'=>'antartica',
 'Región XII Magallanes - Última Esperanza'=>'ultima-esperanza',
 'Región XII Magallanes - Magallanes'=>'magallanes',
 'Región XII Magallanes - Tierra del Fuego'=>'tierra-del-fuego',
 'Región XIV Los Ríos - Valdivia'=>'valdivia',
 'Región XIV Los Ríos - Ranco'=>'ranco',
 'Región XV Arica - Arica'=>'arica',
 'Región XV Arica - Parinacota'=>'parinacota'};
 %>

 
 <div class="top_content">
 <div style="text-align: center;">
   <div class="row">
    <div class="col-lg-5 col-xs-7 wow fadeInUp delay-06s">

  <div class="wrapper">
    <%= form_for ([@client,@cotizacion]) do |f| %>
      <% if @cotizacion.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(cotizacion.errors.count, "error") %> prohibited this cotizacion from being saved:</h2>

          <ul>
            <% cotizacion.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-control">
       <!---De un controlador diferente a vista <3 verifica primero que no exista un profesional asociado -->
      <%if @cotizacion.enterprise_id%>
        <%category_id =Enterprise.where(id: @cotizacion.enterprise_id).pluck(:category_id)%>
       <%=f.hidden_field :enterprise_id,value:@cotizacion.enterprise_id%>
       <%=f.hidden_field :category_id, value: category_id[0]%>
       <%else%>
      <div class= "field">
      <%=f.label :Categoria%>
      <%= f.select :category_id, Category.all.collect {|f| [ "#{f.nombre}",f.id ] }  %>
      </div>
      <%end%>
    
      <div class="field">

       <%= f.label :Area  %>
        <div class="form-control">
       <ul>
        <li><%= f.label :Area, "Rural", :value => "rural"%></li>
        <li><%= f.radio_button :area, "rural"%></li>
        <li><%= f.label :Area, "Urbano", :value => "urbano" %></li>
        <li><%= f.radio_button :area, "urbano" %></li>
        </ul>
      
      </div>
      </div>
      <div class="field">
      
        <%= f.label :Sector %>
        <div class ="form-control">
        <ul>
          <li><%= f.label :Sector, "Publico", :value => "publico"%></li>
          <li><%= f.radio_button :sector, "publico"%></li>
          <li><%= f.label :Sector, "Privado", :value => "privado" %></li>
          <li><%= f.radio_button :sector, "privado" %></li>
        </ul>
      </div>
      </div>
      <div class="field">
        <%= f.label :"Que_necesitas? especifique detalles" %>
        <%= f.text_field :descripcion, size: "80x200" %>
      </div>

      <div class="field">
        <%= f.label :"Cuando espera realizar el proyecto?"%>
         <div class="form-control">
        <ul>
       <li><%= f.label :tiempo , "Lo antes posible", :value => "soon"%></li>
        <li><%= f.radio_button :tiempo, "soon"%></li>
        <li><%= f.label :tiempo , "De 1 a 3 meses", :value => "1a3" %></li>
        <li><%= f.radio_button :tiempo, "1a3" %></li>
        <li><%= f.label :tiempo , "Mas de 3 meses", :value => "mas" %></li>
        <li><%= f.radio_button :tiempo, "mas" %></li>
        </ul>
      </div>
      </div>
      <div class="field">
        <%=f.label :Provincia%><br/>
        <%=f.select :provincia,region%>

      </div>
      </div>

      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
  </div>
  </div>
  <div class="col-lg-6 col-m-7">
        <div class="top_left_cont flipInY wow animated">
            <%= image_tag "win.png", :alt => "", :title => ""%>
        </div>
      </div>
  </div>
  </div>
  </div>

app/views/cotizacions/edit.html.erb
<h1>Editar cotizacion</h1>

<%= render 'form', cotizacion: @cotizacion %>

<%= link_to 'Show', client_cotizacions_path(id:current_client.id) %> 
<%= link_to 'Back', client_cotizacions_path%>

app/views/cotizacions/index.html.erb
<p id="notice"><%= notice %></p>
<div style="text-align: center;">

<h1>Cotizaciones</h1>
</div>

<div class="form-control">

<table>
  <thead>
    <tr>
      <th>Area</th>
      <th>Sector</th>
      <th>Descripcion</th>
      <th>Tiempo</th>
      <th>Empresa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cotizacions.each do |cotizacion| %>
      <tr>
        <td><%= cotizacion.area %></td>
        <td><%= cotizacion.sector %></td>
        <td><%= cotizacion.descripcion %></td>
        <td><%if cotizacion.tiempo = "soon"%>
            <%= "Lo antes posible"%>
            <%elsif cotizacion.tiempo="1a3"%>
            <%="De 1 a 3 meses" %>
            <%else%>
            <%= "Mas de 3 meses"%>
            <%end%>
        </td>
        <td><%=cotizacion.enterprise_id%></td>
        <td><%= link_to 'Edit', edit_client_cotizacion_path(@client,cotizacion) %></td>
        <td><%= link_to 'Destroy',client_cotizacion_path(@client,cotizacion),method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>


<div class="wrapper" style="text-align: center">
<%= link_to 'Nueva cotizacion', new_client_cotizacion_path(current_client.id), class: "buttoncute" %>

<%= link_to "  Volver  ", clientes_path, class: "buttoncute" %>
</div>

app/views/cotizacions/new.html.erb
<div style="text-align: center">
<h1 style="color: red"><strong>Nueva cotizacion</strong></h1>
</div>

<%= render 'form', cotizacion: @cotizacion %>

<div style="text-align: center">
<%= link_to 'Back', clientes_path, class: "buttoncute"%>
</div>

app/views/cotizacions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo:</strong>
  <%= @cotizacion.codigo %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @cotizacion.descripcion %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @cotizacion.estado %>
</p>

<%= link_to 'Edit', edit_client_cotizacion_path(@cotizacion) %> |
<%= link_to 'Back', client_cotizacions_path %>