config/routes.rb
Rails.application.routes.draw do
  captcha_route
  resources :planes
  resources :catalogos
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  post '/rate' => 'rater#create', :as => 'rate'
  resources :catalogos
  resources :categories 
  devise_for :enterprises do
    get '/enterprises/sign_out' => 'devise/sessions#destroy'
end
resources :enterprises do
  resources :answers
end

  devise_for :clients
  root :to => "home#index"
  resources :paginaclients
  resources :paginaentreprise

  #Papa cliente hijo cotizacion
  resources :clients do
  	resources :cotizacions
    resources :calificacions
  end
  get '/solicitudes' => "paginaentrerprise#cotizacionesempresa"
  get '/cotizaciones' => "paginaentrerprise#cotizaciones"
  get '/catalogo' => 'categories#catalogo'
 
  get '/perfil' => 'profile#perfil'
 
  get '/clientes' => 'paginaclients#pageclient'
  get '/profesionales' => 'paginaentrerprise#pagenterprise'

  get '/respuestas_recibidas'=>'paginaclients#respuestas'

  get '/respuesta_aceptada'=>'paginaclients#answer_success'
  get '/nueva_contrasena' => 'paginaclients#new'

  get '/mis_calificaciones' => 'paginaentrerprise#calificacion'


  resources :payments
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
	validates :answer_cotiza, :accept_date, presence: true
	validates_inclusion_of :accept_date, :in => %w(aceptar rechazar)
	belongs_to :enterprise
	belongs_to :cotizacion
	has_one :calificacion
	validates :answer_cotiza, presence: true,length: { maximum: 200 }
	validates :enterprise_id, uniqueness: { scope: :cotizacion_id, message: "¡Ya has entregado tu respuesta!" }

    belongs_to :cotizacion
    belongs_to :enterprise
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "Client"
  belongs_to :rateable, :polymorphic => true
end

app/models/calificacion.rb
class Calificacion < ApplicationRecord
	belongs_to :enterprise
	belongs_to :client
    belongs_to :answer
	validates :comentario, presence: true, length:{in:1..100,  
		too_short:"Debes comentar con un maximo de 100 caracteres el servicio recibido", 
		too_long:"Comentario demasiado largo, maximo 100 caracteres"}
		
	ratyrate_rateable "nota"

	validates :nota, presence: true
	validates :client_id, uniqueness: { scope: :answer_id, message: "¡Ya has entregado tu Calificacion!" }

  
end

app/models/catalogo.rb
class Catalogo < ApplicationRecord
	has_many :categories
	
end

app/models/category.rb
class Category < ApplicationRecord
	belongs_to :catalogo
	has_many :enterprises
	has_many :cotizacions
	validates :area,:nombre, presence: true
	validates_inclusion_of :area, :in => %w(construccion remodelacion)
	validates :nombre, uniqueness: {case_sensitive: false ,message: "ya existe esta categoria"}
	
	
	
end

app/models/client.rb
class Client < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :security_questionable
    has_many :calificacions     
    has_many :cotizacions
  
    validates :rut, :email, :date_of_birth, :provincia, presence: true
    validates :nombre, presence: true, length:{in:4..20, 
  		too_short:"Revisa el nombre ingresado, parece demasiado corto", 
		too_long:"Revisa el nombre ingresado, parece demasiado largo"}
	
  	validates_format_of :apellido, :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/i,message: "Apellido de empresa invalido no se permiten numeros y/o metacaracteres"
	validates_format_of :nombre, :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/i , message: "Nombre invalido no se permiten numeros"
	validates_uniqueness_of :rut
	validates :rut, rut: true, uniqueness: {case_sensitive: false,message:"Oops! ese rut ya esta registrado"}
	 validates :telefono, presence: true
	 validates :telefono, numericality: {only_integer: true}, length: {minimum: 9, maximum: 9, message: "Anteponer 9 a N° celular y 22 a N° de casa"}
	 VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :email, format: { :with => VALID_EMAIL_REGEX, message: "El correo es invalido"}
	# valida que sea correo unico 
	validates :email, uniqueness: {case_sensitives: false, message: "ya esta registrado"}
	#validacion de rut con la gema rut_validation
	validates :rut, rut: true 

	#para ser llamado para calificar
	ratyrate_rater
	validates :date_of_birth, presence: true
end

app/models/cotizacion.rb
class Cotizacion < ApplicationRecord
	has_many :answers
	belongs_to :client
	belongs_to :enterprise
	belongs_to :category
	validates :descripcion, :tiempo, :sector, :area, :provincia,:category_id, presence: true
	validates_inclusion_of :area, :in => %w(rural urbano)
	validates_inclusion_of :sector, :in => %w(publico privado)
	validates_inclusion_of :tiempo, :in => %w(soon 1a3 mas)
	
end

app/models/enterprise.rb
class Enterprise < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :calificacions
  belongs_to :category
  has_many :answers
  has_many :payments
  has_many :cotizacions
  attr_accessor :imagen, :imagen_cache, :remove_imagen
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :telefono, :nombre, :rut, :email,:provincia, presence: true, confirmation: true
	validates :telefono, numericality: {only_integer: true}
	#validates_format_of :nombre, :with => /\A[a-z]+\z/i, message: "Nombre de empresa invalido no se permiten numeros"
	validates_format_of :nombre, :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/i,message: "Nombre de empresa invalido no se permiten numeros y/o metacaracteres"
  validates_format_of :apellido, :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/i,message: "Apellido de empresa invalido no se permiten numeros y/o metacaracteres"
  #validacion correo 
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i 
	validates :email, format: { :with => VALID_EMAIL_REGEX, message: "El correo es invalido"},uniqueness:{case_sensitives: false, message: "Este email ya se encuentra registrado"}
	# valida que sea correo unico 
	validates :email, uniqueness: {case_sensitives: false, message: "ya esta registrado"}
	#valida que este correcto el mail 

	validates :rut, rut: true, uniqueness: {case_sensitives: false, message:"Este rut ya se encuentra registrado"}
  validates_uniqueness_of :rut
	#imagen para referenciar donde se subira logo mediante clase FotoUploader
	mount_uploader :imagen, FotoUploader
	#+++++++++++++++++++++++++++++++++++++++
  	validates_presence_of   :imagen
  	validates_integrity_of  :imagen
  	validates_processing_of :imagen

  
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :enterprises
  belongs_to :plan




  attr_accessor :imagen, :imagen_cache, :remove_imagen
  mount_uploader :imagen, FotoUploader
  #+++++++++++++++++++++++++++++++++++++++
    validates_presence_of   :imagen
    validates_integrity_of  :imagen
    validates_processing_of :imagen

 
  def tiempos
    if Time.now > self.tiempo_termino 
      self.tiempo_termino= 0
      self.canceled = false
    end
  end


 
end

app/models/plane.rb
class Plane < ApplicationRecord
	has_many :payments
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "Client"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/planes_helper.rb
module PlanesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/home/index.html.erb
<!doctype html>
<html>
<header>

  <title>jQuery UI Datepicker - Estilo Cupertino</title>
      <link rel="css" href="jquery-ui-1.10.2.cupertino.css" />
      <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
      <script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script>
      <script src="jquery.ui.datepicker-es.js"></script>

      <script>
      $(function () {
      $.datepicker3.setDefaults($.datepicker3.regional["es"]);
      $("#datepicker").datepicker({
        firstDay: 1
        });
        });
      </script>
      <meta charset="utf-8" />
      <title>jQuery UI Datepicker - onSelect</title>
      <link rel="css" href="http://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css" />
      <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
      <script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script>
      <script src="jquery.ui.datepicker-es.js"></script>

      <script>
      $(function () {
      $.datepicker3.setDefaults($.datepicker3.regional["es"]);
      $("#datepicker").datepicker3({
      firstDay: 1,
      onSelect: function (date) {
      alert(date)
      },
      });
      });
      </script>


 <div class="container">
      <nav class="nav" id="nav">
        <ul class="toggle">
          <li><a href="#top_content"></a>Inicio</li>
          <li><a href="#suscripcion">Suscripcion</a></li>
          <li><a href="#client_outer">Clientes</a></li>
          <li><a href="#empresa">Empresa</a></li>
          <li><a href="#contact">Contacto</a></li>
        </ul>
        <ul class="">
          <li><%=link_to "Inicio",root_path%></li>
          <li><a href="#suscripcion">Suscripcion</a></li>
          <li><%=link_to "Clientes",clientes_path%></li>
          <li><%=link_to "Empresas",profesionales_path%></li>
          <li><a href="#contact">Contacto</a></li>
        </ul>
        </div>

      </nav>
  </div>
</header>
<body>


<!--Top_content-->
  <div class="top_cont_inner">
    <div class="container">
      <div class="top_content">
        <div class="row">
          <div class="col-lg-5 col-sm-7">
            <div class="top_left_cont flipInY wow animated">
              <h3>Cotizar &amp; Facil!</h3>
              <h2>Reciba presupuestos de profesionales:
Pintores, carpinteros, remodelación de viviendas, mudanzas &amp; más…</h2>
          </div>
        </div>
        <div class="col-lg-4 col-xs-7">
        <div class="top_left_cont flipInY wow animated">
            <%= image_tag "trabajadorok.png", :alt => "", :title => ""%>
        </div>
      </div>
      </div>
    </div>
  </div>
<section  id="service">
  <div class="container">
    <div class="service_area">
      <div class="row">
        <div class="col-lg-4">
          <div class="service_block">
            <div class="service_icon delay-03s animated wow  zoomIn"> <span><i class="fa fa-thumbs-o-up"></i></span> </div>
            <h3 class="animated fadeInUp wow">Es gratis</h3>
            <p class="animated fadeInDown wow">Reciba varios presupuestos de forma gratuita y sin compromiso.</p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="service_block">
            <div class="service_icon icon2  delay-03s animated wow zoomIn"> <span><i class="fa fa-money"></i></span> </div>
            <h3 class="animated fadeInUp wow">Ahorre dinero</h3>
            <p class="animated fadeInDown wow">Reciba varios presupuesto para poder comparar.</p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="service_block">
            <div class="service_icon icon3  delay-03s animated wow zoomIn"> <span><i class="fa fa-certificate"></i></span> </div>
            <h3 class="animated fadeInUp wow">Trabajos</h3>
            <p class="animated fadeInDown wow">Encuentre trabajos y aproveche nuestras ventajas.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!--Service-->
<section class="main-section" id="suscripcion">
<div class="suscripcion_section animated  fadeInUp wow">
  <div style="text-align: center">
    <h2 style="text-align: center"> Suscribete ahora! </h2>
  </div>
<ul>
  <li>
    <h3 style="text-align: center;">Clientes</h3>
    <br>
    <div style="text-align: center;">
    <br>
        <%=link_to "Suscribirse",new_client_registration_path, class: "buttoncute"%>
    </div>
    <br>
  </li>
  <br>
  <li>
    <h3 style="text-align: center;">Profesionales</h3>
    <br>
      <div style="text-align: center;">
      <br>
        <%=link_to "Suscribirse",new_enterprise_registration_path, class: "buttoncute"%> 
      </div>
  </li>
</ul>
      </div>
    </div>
</section>
<br>

<section class="twitter-feed">
  <div class="container  animated fadeInDown delay-07s wow">
    <h3>Encuentre empresas en nuestro directorio, Consulte precios para su proyecto y escoga la mejor cotizacion</h3>
    <%=image_tag "constructor.jpg"%>
    </div>
</section>

<footer class="footer_section" id="contact">
  <div class="container">
    <section class="main-section contact" id="contact">
      <div class="contact_section">
        <h2>Contactenos</h2>
        <div class="row">
          <div class="col-lg-4">
            <div class="contact_block">
              <div class="contact_block_icon rollIn animated wow"><span><i class="fa-home"></i></span></div>
              <span> Napoleon 3565 Oficina 202, <br>
               Las Condes
              EDIFICIO STUDIO II - EL GOLF </span> </div>
          </div>
          <div class="col-lg-4">
            <div class="contact_block">
              <div class="contact_block_icon icon2 rollIn animated wow"><span><i class="fa-phone"></i></span></div>
              <span> 222-037-495 </span> </div>
          </div>
          <div class="col-lg-4">
            <div class="contact_block">
              <div class="contact_block_icon icon3 rollIn animated wow"><span><i class="fa-pencil"></i></span></div>
              <span> <a href="mailto:hello@butterfly.com"> easy.cotiza@gmail.com</a> </span> </div>
          </div>
        </div>
      </div>

    </section>
  </div>
 
</footer>
<script type="text/javascript">
    $(document).ready(function(e) {
        $('#header_outer').scrollToFixed();
        $('.res-nav_click').click(function(){
            $('.main-nav').slideToggle();
            return false    
            
        });
        
    });
</script> 
<script>
    wow = new WOW(
      {
        animateClass: 'animated',
        offset:       100
      }
    );
    wow.init();
    document.getElementById('').onclick = function() {
      var section = document.createElement('section');
      section.className = 'wow fadeInDown';
    section.className = 'wow shake';
    section.className = 'wow zoomIn';
    section.className = 'wow lightSpeedIn';
      this.parentNode.insertBefore(section, this);
    };
  </script> 
<script type="text/javascript">
  $(window).load(function(){
    
    $('a').bind('click',function(event){
      var $anchor = $(this);
      
      $('html, body').stop().animate({
        scrollTop: $($anchor.attr('href')).offset().top - 91
      }, 1500,'easeInOutExpo');
      /*
      if you don't want to use the easing effects:
      $('html, body').stop().animate({
        scrollTop: $($anchor.attr('href')).offset().top
      }, 1000);
      */
      event.preventDefault();
    });
  })
</script> 

<!--<script type="text/javascript">

$(window).load(function(){
  
  
  var $container = $('.portfolioContainer'),
      $body = $('body'),
      colW = 350,
      columns = null;

  
  $container.isotope({
    // disable window resizing
    resizable: true,
    masonry: {
      columnWidth: colW
    }
  });
  
  $(window).smartresize(function(){
    // check if columns has changed
    var currentColumns = Math.floor( ( $body.width() -30 ) / colW );
    if ( currentColumns !== columns ) {
      // set new column count
      columns = currentColumns;
      // apply width to container manually, then trigger relayout
      $container.width( columns * colW )
        .isotope('reLayout');
    }
    
  }).smartresize(); // trigger resize to set container width
  $('.portfolioFilter a').click(function(){
        $('.portfolioFilter .current').removeClass('current');
        $(this).addClass('current');
 
        var selector = $(this).attr('data-filter');
        $container.isotope({
      
            filter: selector,
         });
         return false;
    });
  
});

</script>


--> 

<script type="text/javascript">

   
  jQuery(document).ready(function($){     
// Portfolio Isotope
  var container = $('#portfolio-wrap'); 
  

  container.isotope({
    animationEngine : 'best-available',
      animationOptions: {
        duration: 200,
        queue: false
      },
    layoutMode: 'fitRows'
  }); 

  $('#filters a').click(function(){
    $('#filters a').removeClass('active');
    $(this).addClass('active');
    var selector = $(this).attr('data-filter');
      container.isotope({ filter: selector });
        setProjects();    
      return false;
  });
    
    
    function splitColumns() { 
      var winWidth = $(window).width(), 
        columnNumb = 1;
      
      
      if (winWidth > 1024) {
        columnNumb = 4;
      } else if (winWidth > 900) {
        columnNumb = 2;
      } else if (winWidth > 479) {
        columnNumb = 2;
      } else if (winWidth < 479) {
        columnNumb = 1;
      }
      
      return columnNumb;
    }   
    
    function setColumns() { 
      var winWidth = $(window).width(), 
        columnNumb = splitColumns(), 
        postWidth = Math.floor(winWidth / columnNumb);
      
      container.find('.portfolio-item').each(function () { 
        $(this).css( { 
          width : postWidth + 'px' 
        });
      });
    }   
    
    function setProjects() { 
      setColumns();
      container.isotope('reLayout');
    }   
    
    container.imagesLoaded(function () { 
      setColumns();
    });
    
  
    $(window).bind('resize', function () { 
      setProjects();      
    });

});
$( window ).load(function() {
  jQuery('#all').click();
  return false;
});
</script>
</body>
</html>
</html>