config/routes.rb
Rails.application.routes.draw do
  captcha_route
  resources :planes
  resources :catalogos
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  post '/rate' => 'rater#create', :as => 'rate'
  resources :catalogos
  resources :categories 
  devise_for :enterprises do
    get '/enterprises/sign_out' => 'devise/sessions#destroy'
end
resources :enterprises do
  resources :answers
end

  devise_for :clients
  root :to => "home#index"
  resources :paginaclients
  resources :paginaentreprise

  #Papa cliente hijo cotizacion
  resources :clients do
  	resources :cotizacions
    resources :calificacions
  end
  get '/solicitudes' => "paginaentrerprise#cotizacionesempresa"
  get '/cotizaciones' => "paginaentrerprise#cotizaciones"
  get '/catalogo' => 'categories#catalogo'
 
  get '/perfil' => 'profile#perfil'
 
  get '/clientes' => 'paginaclients#pageclient'
  get '/profesionales' => 'paginaentrerprise#pagenterprise'

  get '/respuestas_recibidas'=>'paginaclients#respuestas'

  get '/respuesta_aceptada'=>'paginaclients#answer_success'
  get '/nueva_contrasena' => 'paginaclients#new'

  get '/mis_calificaciones' => 'paginaentrerprise#calificacion'


  resources :payments
end

app/controllers/paginaclients_controller.rb
class PaginaclientsController < ApplicationController
	before_action :authenticate_client!, except: [:new]

	def pageclient
		 @client = current_client
    	@cotizacions= Cotizacion.where(client_id: @client.id)
	end

	def respuestas
		@cotizaciones =Cotizacion.where(client_id: current_client.id).limit(5)
		@respuestas= Answer.where(cotizacion_id: @cotizaciones.ids)
	end


	def answer_success

		if params[:answer]
			@respuesta = Answer.find(params[:answer])
			@respuesta.estado = true
			@enterprise = Enterprise.where(id: @respuesta.enterprise_id)
			
		end

	end

	def new
	 	@client = Client.find_by_email(params[:email])
	 	respond_to do |format|
  		format.html
		end


	end

	
	
	
end

app/helpers/paginaclients_helper.rb
module PaginaclientsHelper
end

app/views/paginaclients/answer_success.html.erb
<html>
<body>

      <div class="container" style="padding-top: 5cm">
     <div class="row" >
        <div class="col-lg-4 col-m-7">
    		

				<%@enterprise.each do |empresa|%>
					<figure>
					<figcaption>
    				<picture>
     				 <%=image_tag empresa.imagen,class: "avatar"%>
    				</picture>
					<h1 class="name"><%= empresa.nombre%></h1>
     				 <h3 class="title"><%=empresa.descripcion%></h3>
      				<h4><%=empresa.telefono%></h4>
      				<h4><%=empresa.email%></h4>
      				 </figcaption>
      				</figure>
  				   <%=link_to "Calificar",new_client_calificacion_path(current_client.id, :enterprise_id => empresa.id, :respuesta => @respuesta)%>
    				<%end%>
  				
  		
  		</div>

  </div>

</div>
  </body>
</html>

app/views/paginaclients/new.html.erb
<h2>Forgot your password?</h2>

<%= form_for(@client) do |f| %>
  <div class="field">
    <%= f.label :password, "Password" %><br />
    <%= f.password_field :password, :autocomplete => "off"  %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="action_container">
    <%= f.submit %>
  </div>
<% end %>

app/views/paginaclients/pageclient.html.erb
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <link rel="icon" type="image/png" href="assets/img/favicon.ico">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />


    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />


    <!-- Bootstrap core CSS     -->
    <link href="assets/css/bootstrap.min.css" rel="stylesheet" />



    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="assets/css/pe-icon-7-stroke.css" rel="stylesheet" />

</head>
<body>
    <div class="main-panel">
        <nav class="navbar navbar-default" style="padding-top: 0%" >
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <p class="navbar-brand"><%= current_client.email %> </p>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-left" >
                        <li>
                            <a class="dropdown-toggle">
                                <i class="fa fa-user" aria-hidden="true"></i>
                                <%=current_client.nombre%>
                            </a>
                        </li>
                    
                        <li>
                           <a href="">
                    
                            </a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                        
                           <%= link_to "Editar perfil",edit_client_registration_path %> 
                        </li>

             
                        <li class="dropdown" aria-labelledby="menu"> 
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    Menu
                                    <b class="caret"></b>
                              </a>
                              <ul class="dropdown-menu">
                                <li><%= link_to "Historial de calificaciones", client_calificacions_path(current_client.id) %></li>
                                <li><%=link_to "Respuestas recibidas",respuestas_recibidas_path%></li>
                                <li><%=link_to "Ver empresas", categories_path%></li>
            
                              </ul>
                        </li>
                      
                        <li>
                            <%=link_to "Cerrar sesion", destroy_client_session_path, :method => :delete%>

                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        </div>

 <div class="top_cont_inner" >
      <div class="container-fluid">
      <div class="top_content">
        <div class="row" >
        <div class="col-xs-2">
        <div style="text-align: right;">
            <%=image_tag("trabajador.png", width: 90, heigth:90)%>
            </div>
        </div>
        <div class="col-xs-2 col-xs-2">
        <div class="top_left_cont flipInY wow animated" style="padding-top: 0px">
        <div style="text-align: center;">
              <h3 style="text-align: center;">Cotiza ahora!</h3>
            
              <p><%=link_to "Cotizar", new_client_cotizacion_path(current_client.id), class: "buttonsombra"%></p>
         </div>
        </div>
    </div>

        
        <div class="col-lg-5 col-xs-6">
        <div class="top_left_cont flipInY wow animated" style="padding-top: 0px">
        <h3 style="text-align: center;"> Cotizaciones sin respuesta </h3>
        <div class ="form-control">
        <table>
            <thead>
                <tr>
                    <th>Descripcion</th>
                    <th>Categoria</th>
                    <th>Subida el </th>
                    <th colspan="3"></th>
                </tr>
            </thead>

        <tbody>
    
            <%@cotizacions.each do |cotizacion|%>
                <%if not (Answer.exists? id: cotizacion.id) %>
           
                <tr>
                    <td><%=cotizacion.descripcion%></td>
                    <td><% categoria=Category.where(id: cotizacion.category_id).pluck(:nombre)%>
                        <%=categoria[0]%> </td>
                    <td><%=cotizacion.created_at.strftime("%d/%b/%Y")%></td>
                
                </tr>
            <%end%>
        <%end%>
        </tbody>
        </table>
        </div>
        </div>
        </div>

        <div class="col-lg-2  col-xs-2 sidebar text right " >
        <div class="list-group">
  <a class="list-group-item" href="/"><i class="fa fa-home fa-fw" aria-hidden="true"></i>&nbsp; Inicio</a>

  <a class="list-group-item" href="/respuestas_recibidas"><i class="fa fa-pencil fa-fw" aria-hidden="true"></i>&nbsp; Respuestas</a>
</div>
    </div>
    
    </div>
</div>

</div>

</div>
</body>

    <!--   Core JS Files   -->
    <script src="assets/js/jquery-1.10.2.js" type="text/javascript"></script>
    <script src="assets/js/bootstrap.min.js" type="text/javascript"></script>

    <!--  Checkbox, Radio & Switch Plugins -->
    <script src="assets/js/bootstrap-checkbox-radio-switch.js"></script>

    <!--  Charts Plugin -->
    <script src="assets/js/chartist.min.js"></script>

    <!--  Notifications Plugin    -->
    <script src="assets/js/bootstrap-notify.js"></script>

    <!--  Google Maps Plugin    -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>

</html>

app/views/paginaclients/respuestas.html.erb
<p id="notice"><%= notice %></p>
<div style="text-align: center;">

<h1 style="color:red"><strong>Respuestas recibidas</strong></h1>
</div>
<div class ="container">
<div class="form-control" style="text-align: center;">

<ul>
    <% @cotizaciones.each do |cotizacion| %>
     <%if (Answer.exists? id: cotizacion.id) %>
     <h3> <i class="fa fa-bookmark-o" aria-hidden="true" style="font-size: 20px;color:red"></i> Cotizacion n° <%=cotizacion.id%></h3>
          
           <li>
<textarea rows="10" cols="90" readonly><%= cotizacion.descripcion %> 
</textarea></li>
<br>
    <%cotizacion.answers.each do|respuesta|%>
  
      
       <div class="form-control" style="text-align: left">
       <p style="text-align: right;"><%=link_to "Aceptar",respuesta_aceptada_path(:answer => respuesta), class: "button3"%></p>

        <li><% empresa= Enterprise.where(id: respuesta.enterprise_id).pluck( :nombre)%>
        <p><i class="fa fa-user" aria-hidden="true" style="font-size: 20px"></i><u><%=empresa[0]%></u> :</p>
        </li>
        <li>Fecha a realizar el proyecto : <%= respuesta.fecha %></li>
        <li><%= respuesta.answer_cotiza %></li>
      </div>
      
    <% end %>
    <%end%>
    <%end%>
</ul>
<br>
</div>


<div class="wrapper" style="text-align: center">


<%= link_to "  Volver  ", :back, class: "buttoncute" %>
</div>
</div>