config/routes.rb
Rails.application.routes.draw do
  captcha_route
  resources :planes
  resources :catalogos
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  post '/rate' => 'rater#create', :as => 'rate'
  resources :catalogos
  resources :categories 
  devise_for :enterprises do
    get '/enterprises/sign_out' => 'devise/sessions#destroy'
end
resources :enterprises do
  resources :answers
end

  devise_for :clients
  root :to => "home#index"
  resources :paginaclients
  resources :paginaentreprise

  #Papa cliente hijo cotizacion
  resources :clients do
  	resources :cotizacions
    resources :calificacions
  end
  get '/solicitudes' => "paginaentrerprise#cotizacionesempresa"
  get '/cotizaciones' => "paginaentrerprise#cotizaciones"
  get '/catalogo' => 'categories#catalogo'
 
  get '/perfil' => 'profile#perfil'
 
  get '/clientes' => 'paginaclients#pageclient'
  get '/profesionales' => 'paginaentrerprise#pagenterprise'

  get '/respuestas_recibidas'=>'paginaclients#respuestas'

  get '/respuesta_aceptada'=>'paginaclients#answer_success'
  get '/nueva_contrasena' => 'paginaclients#new'

  get '/mis_calificaciones' => 'paginaentrerprise#calificacion'


  resources :payments
end

app/models/category.rb
class Category < ApplicationRecord
	belongs_to :catalogo
	has_many :enterprises
	has_many :cotizacions
	validates :area,:nombre, presence: true
	validates_inclusion_of :area, :in => %w(construccion remodelacion)
	validates :nombre, uniqueness: {case_sensitive: false ,message: "ya existe esta categoria"}
	
	
	
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    @construccion= Category.where(area: "construccion")
    @remodelacion=Category.where(area: "remodelacion")


  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Categoria creada.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Categoria editada' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Eliminado de categoria exitoso.' }
      format.json { head :no_content }
    end
  end

  def catalogo

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:area, :nombre,:enterprise_id,:client_id,:id,:cotizacion_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :Area %>
      <ul>
      <li><%= f.label :Area, "Construccion", :value => "construccion"%></li>
        <li><%= f.radio_button :area, "construccion"%></li>
        <li><%= f.label :Area, "Remodelacion", :value => "remodelacion" %></li>
        <li><%= f.radio_button :area, "remodelacion" %></li>
      </ul>
  </div>
  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre, placeholder: "Nombre de Categoria" %>
  </div>

  <div class="actions">
    <%= f.submit "Guardar", class:"btn be-red white" %>
  </div>
<% end %>

app/views/categories/catalogo.html.erb
<head>


<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,200,300,600,700' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="bootstrap/css/bootstrap.css" />
<link rel="stylesheet" type="text/css" href="css/style.css">
<link rel="stylesheet" type="text/css" href="bootstrap/css/bootstrap-responsive.css" />
<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

</head>

<body>

<header class="hidden-phone">
  <h2 class="header-title">Empresas</h2>
</header>
 
 
<div class="container">
<div class= "form-control">
  
  #para filtrar por categorias

<div class="wrapper">
<% form_for ([@enterprises,@category]) do |f| %>
<% if @cotizacion.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(cotizacion.errors.count, "error") %> prohibited this cotizacion from being saved:</h2>

  <div class= "field">
      <%=f.label :Categoria%>
      <%= f.select :category_id, Category.all.collect {|f| [ "#{f.nombre}",f.id ] }  %>


<div style ="text-align: left;">
  <% if category_id == nil %>
    <% @enterprises.each do |empresa| %>
      <table>
        <th colspan="3"></th>
          <tr style="text-align: center;">
            <td><%=image_tag(empresa.imagen,:width =>100 , :height => 100)%> </td>
            <h3><%=empresa.nombre%></h3></td>
            <td><h4>Descrpcion: <%=empresa.descripcion%></h4></td>
            <td><h4>Provincia: <%=empresa.provincia%></h4></td>
            <td><h4>Fecha de incorporacion a EasyCotiza: <%=empresa.fecha_de_inicio%></h4></td>
          </tr>
      </table>
    <%end%>
  <% else %>
    <% @enterprises.each_with_index do |empresa, category_id| %>
      <table>
        <th colspan="3"></th>
          <tr style="text-align: center;">
            <td><%=image_tag(empresa.imagen,:width =>100 , :height => 100)%> </td>
            <h3><%=empresa.nombre%></h3></td>
            <td><h4>Descrpcion: <%=empresa.descripcion%></h4></td>
            <td><h4>Provincia: <%=empresa.provincia%></h4></td>
            <td><h4>Fecha de incorporacion a EasyCotiza: <%=empresa.fecha_de_inicio%></h4></td>
          </tr>
      </table>
    <%end%>
  <% end %>
</div>
</div>


</div>
<%end%>
<%end%>
</div>


  #<div style="text-align: left;">
  #<% @enterprises.each do |empresa| %>
  #<table>
  # <th colspan="3"></th>
  #  	<tr style="text-align: center;">
  # 	    <td><%=image_tag(empresa.imagen,:width =>100 , :height => 100)%> </td>
  #		 <h3><%=empresa.nombre%></h3></td>
  #      <td><h4>Descrpcion: <%=empresa.descripcion%></h4></td>
  #      <td><h4>Provincia: <%=empresa.provincia%></h4></td>
  #      <td><h4>Fecha de incorporacion a EasyCotiza: <%=empresa.fecha_de_inicio%></h4></td>
  #      </tr>
  #</table>
  #<%end%>
  #</div>

</div>
</div>
 
    
  <div class="row">
    <div class="span12">
      <ul class="pager">
        <li class="previous"> <a href="#">&larr; Previous</a></li>
        <li class="next"> <a href="#">Next &rarr;</a></li>
      </ul>
    </div>
  </div>
  
</body>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>
<div style="text-align: center">
  <h2>Categorias</h2>
</div>


 <div class="container">
  <div class="top_content">
  <div class="row">
  <div class="col-lg-5 col-m-7">
  <h3 style="text-align: center;">Construcciones</h3>

  <div class ="form-control" align="center">
      <table>
        <% @construccion.each do |category| %>
          <tr>
            <%if category.nombre =="construccion casa"%>
              <td>
                <h3>Construccion de casas </h3>
                <%= link_to image_tag("construccioncasa.png", :alt => "construccion de casas",:width => 40, :height => 40),catalogos_path(:category_id=>1),class: "button2"%>
               </td>
            <% elsif category.nombre=="construccion edificio"%>
              <td>
                <h3>Construccion de edificios </h3>
                <%=link_to image_tag("construccionedificio.png", :alt => "construccion de edificios",:width => 40, :height => 40), catalogos_path(:category_id=>2), class: "button2"%>
              </td>

            <%elsif category.nombre =="construccion galpones"%>
              <td>
                <h3>Construccion de galpones </h3>
                <%=link_to image_tag("galpon.png", :alt => "construccion de galpones",:width => 40, :height => 40),catalogos_path(:category_id=>3), class: "button2"%>
 
              </td>

            <%elsif category.nombre=="construccion Piscina"%>
              <td>
                <h3>Construcciones de piscinas </h3>
                  <%=link_to image_tag("piscina.png", :alt => "construccion de piscinas",:width => 40, :height => 40), catalogos_path(:category_id=> 4), class: "button2"%>
              </td>

            <%elsif category.nombre=="arquitectos"%>
               <td>
                 <h3>Arquitectos</h3>
                 <%=link_to image_tag("arquitecto.png", :alt => "arquitectos",:width => 40, :height => 40), catalogos_path(:category_id=>5), class: "button2"%>
               </td>

            <%elsif category.nombre=="demoliciones"%>
              <td>
                <h3>Demoliciones</h3>
                <%=link_to image_tag("demolicion.png", :alt => "demoliciones",:width => 40, :height => 40), catalogos_path(:category_id=>6), class: "button2"%>
              </td>

            <%elsif category.nombre=="instalaciones deportivas"%>
              <td>
                <h3>Instalaciones deportivas</h3>
                <%=link_to image_tag("instalacionesdeportivas.png", :alt => "Instalaciones deportivas",:width => 40, :height => 40), catalogos_path(:category_id=>7), class: "button2"%>
              </td>

            <%elsif category.nombre=="excavaciones"%>
              <td>
                <h3>Excavaciones</h3>
                <%=link_to image_tag("excavacion.png", :alt => "Excavaciones",:width => 40, :height => 40), catalogos_path(:category_id=>8), class: "button2"%>
              </td>
            <%elsif category.nombre=="ingenieros"%>
              <td>
                <h3>Ingenieros</h3>
                <%=link_to image_tag("arquitecto.png", :alt => "Ingeniero",:width => 40, :height => 40), catalogos_path(:category_id=>9), class: "button2"%>
              </td>

            <%end%>
          </tr>
        <%end%>
  
    </table>
  </div>
</div>

<div class="col-lg-5 col-m-7 text right">
 <h3 style="text-align: center;">Remodelaciones</h3>
  <div class ="form-control">
      <table>
        <% @remodelacion.each do |category| %>
        <tr>
          <%if category.nombre=="aire acondicionado"%>
          <td>
            <h3>Aire acondicionado</h3>
             <%=link_to image_tag("aireacondicionado.png", :alt => "Aire acondicionado",:width => 40, :height => 40), catalogos_path(:category_id=>10),class: "button2"%>
          </td>

          <%elsif category.nombre=="aislamiento termico"%>
            <td>
              <h3>Aislamiento termico</h3>
                <%=link_to image_tag("aislamientotermico.png", :alt => "Aislamiento termico",:width => 40, :height => 40), catalogos_path(:category_id=>11),class: "button2"%>
            </td>
          <%elsif category.nombre=="ascensores"%>
          <td>
            <h3>Ascensores</h3>
            <%=link_to image_tag("ascensores.png", :alt => "ascensores",:width => 40, :height => 40), catalogos_path(:category_id=>12),class: "button2"%>
          </td>
          <%elsif category.nombre=="albañil"%>
          <td>
            <h3>Albañiles</h3>
            <%=link_to image_tag("arquitecto.png", :alt => "Albañil",:width => 40, :height => 40), catalogos_path(:category_id=>13),class: "button2"%>
          </td>
          <%elsif category.nombre=="calefaccion"%>
          <td>
            <h3>Calefaccion</h3>
            <%=link_to image_tag("calefaccion.png", :alt => "calefaccion",:width => 40, :height => 40), catalogos_path(:category_id=>14),class: "button2"%>
          </td>
          <%elsif category.nombre=="carpinteria"%>
          <td>
            <h3>Carpinteria</h3>
            <%=link_to image_tag("arquitecto.png", :alt => "Carpintero",:width => 40, :height => 40), catalogos_path(:category_id=>15),class: "button2"%>
          </td>

          <%elsif category.nombre=="domotica"%>
          <td>
            <h3>Domotica</h3>
            <%=link_to image_tag("domotica.png", :alt => "Domotica",:width => 40, :height => 40), catalogos_path(:category_id=>16),class: "button2"%>
          </td>
          <%elsif category.nombre=="electricistas"%>
          <td>
            <h3>Electricistas</h3>
            <%=link_to image_tag("electricista.png", :alt => "Electricistas",:width => 40, :height => 40), catalogos_path(:category_id=>17),class: "button2"%>
          </td>
          <%elsif category.nombre=="gasfiteria"%>
          <td>
            <h3>Gasfiteria</h3>
            <%=link_to image_tag("gasfiteria.png", :alt => "Gasfiteria",:width => 40, :height => 40), catalogos_path(:category_id=>18),class: "button2"%>
          </td>
          <%elsif category.nombre=="insonorizacion"%>
          <td>
            <h3>Insonorizacion</h3>
            <%=link_to image_tag("insonorizacion.png", :alt => "Insonorizacion",:width => 40, :height => 40), catalogos_path(:category_id=>19),class: "button2"%>
          </td>
          <%elsif category.nombre=="pintores"%>
          <td>
            <h3>Pintores</h3>
            <%=link_to image_tag("pintores.png", :alt => "Pintores",:width => 40, :height => 40), catalogos_path(:category_id=>20),class: "button2"%>
          </td>
          <%elsif category.nombre=="pisos"%>
          <td>
            <h3>Pisos</h3>
            <%=link_to image_tag("pisos.png", :alt => "Pisos",:width => 40, :height => 40), catalogos_path(:category_id=>21),class: "button2"%>
          </td>
          <%elsif category.nombre=="jardin"%>
          <td>
            <h3>Jardineria</h3>
            <%=link_to image_tag("jardineria.png", :alt => "Jardineria",:width => 40, :height => 40), catalogos_path(:category_id=>22),class: "button2"%>
          </td>
          <%elsif category.nombre=="seguridad"%>
          <td>
            <h3>Seguridad</h3>
            <%=link_to image_tag("seguridad.png", :alt => "Seguridad",:width => 40, :height => 40), catalogos_path(:category_id=>23),class: "button2"%>
          </td>
          <%elsif category.nombre=="techos"%>
          <td>
            <h3>Techos</h3>
            <%=link_to image_tag("techos.png", :alt => "Techos",:width => 40, :height => 40), catalogos_path(:category_id=>24),class: "button2"%>
          </td>

          <%elsif category.nombre=="toldos"%>
          <td>
            <h3>Toldos</h3>
            <%=link_to image_tag("toldos.png", :alt => "Toldos",:width => 40, :height => 40), catalogos_path(:category_id=>25),class: "button2"%>
          </td>

          <%elsif category.nombre=="yeseros"%>
          <td>
            <h3>Yeseros</h3>
            <%=link_to image_tag("yesero.png", :alt => "Yeseros",:width => 40, :height => 40), catalogos_path(:category_id=>26),class: "button2"%>
          </td>

          <%elsif category.nombre=="ventanas"%>
          <td>
            <h3>Ventanas</h3>
            <%=link_to image_tag("ventana.png", :alt => "Ventana",:width => 40, :height => 40), catalogos_path(:category_id=>27),class: "button2"%>
          </td>
            

          <%end%>
        </tr>
        <%end%>
      </table>
    </div>
</div>
</div>
</div>
<div style="text-align: center;">
  <%=link_to "Volver",clientes_path ,class: "buttoncute"%>
</div>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @category.nombre %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>